### ISSUE TITLE
Schmooze::JavaScript::ReferenceError

### ISSUE THREAD

**Issue by urimaro** [fnando/using-es6-with-asset-pipeline-on-ruby-on-rails#1]
The reference error has occurred.
What do I have to do?
# Steps to reproduce

```
$ git clone https://github.com/fnando/using-es6-with-asset-pipeline-on-ruby-on-rails.git
$ cd using-es6-with-asset-pipeline-on-ruby-on-rails
$ bundle install --path vendor/bundle
$ bundle exec rails s
```

Access 'http://localhost:3000/'.
# Actual behavior

```
Showing /Users/goh/Rails/using-es6-with-asset-pipeline-on-ruby-on-rails/app/views/layouts/application.html.erb where line #5 raised:

Unknown plugin "external-helpers" specified in "base" at 0, attempted to resolve relative to "/Users/goh/Rails/using-es6-with-asset-pipeline-on-ruby-on-rails/app/assets/javascripts/application"
```

Full Trace:

```
app/assets/config/manifest.js:2
vendor/bundle/ruby/2.3.0/gems/schmooze-0.1.6/lib/schmooze/base.rb:117:in `call_js_method'
vendor/bundle/ruby/2.3.0/gems/schmooze-0.1.6/lib/schmooze/base.rb:28:in `block in method'
vendor/bundle/ruby/2.3.0/gems/babel-schmooze-sprockets-0.1.2/lib/babel-schmooze-sprockets/babel_processor.rb:66:in `block in call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cache.rb:85:in `fetch'
vendor/bundle/ruby/2.3.0/gems/babel-schmooze-sprockets-0.1.2/lib/babel-schmooze-sprockets/babel_processor.rb:46:in `call'
vendor/bundle/ruby/2.3.0/gems/babel-schmooze-sprockets-0.1.2/lib/babel-schmooze-sprockets/babel_processor.rb:29:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:83:in `call_processor'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:65:in `block in call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `reverse_each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:21:in `block in <class:CompositeProcessor>'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:32:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:83:in `call_processor'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:65:in `block in call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `reverse_each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:147:in `load_from_unloaded'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:58:in `block in load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:42:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:47:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/bundle.rb:23:in `block in call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/utils.rb:152:in `dfs'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/bundle.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:83:in `call_processor'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:65:in `block in call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `reverse_each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:147:in `load_from_unloaded'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:58:in `block in load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:42:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:47:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:384:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:353:in `block in link_paths'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:363:in `block in resolve_paths'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:359:in `each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:359:in `resolve_paths'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:352:in `link_paths'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:313:in `process_link_directory_directive'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:176:in `block in process_directives'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:174:in `each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:174:in `process_directives'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:79:in `_call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/directive_processor.rb:64:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:83:in `call_processor'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:65:in `block in call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `reverse_each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:147:in `load_from_unloaded'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:58:in `block in load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:42:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:47:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/bundle.rb:23:in `block in call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/utils.rb:152:in `dfs'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/bundle.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:83:in `call_processor'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:65:in `block in call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `reverse_each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/processor_utils.rb:64:in `call_processors'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:147:in `load_from_unloaded'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:58:in `block in load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/loader.rb:42:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/cached_environment.rb:47:in `load'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/base.rb:66:in `find_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/manifest.rb:124:in `block in find'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/manifest.rb:123:in `each'
vendor/bundle/ruby/2.3.0/gems/sprockets-4.0.0.beta2/lib/sprockets/manifest.rb:123:in `find'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:49:in `each'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:49:in `map'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:49:in `precompiled_assets'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:34:in `asset_precompiled?'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:214:in `block (3 levels) in <class:Railtie>'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:345:in `precompiled?'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:349:in `raise_unless_precompiled_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:334:in `find_debug_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:216:in `block in lookup_debug_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:229:in `block in resolve_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:228:in `each'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:228:in `detect'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:228:in `resolve_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:215:in `lookup_debug_asset'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:157:in `block in stylesheet_link_tag'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:156:in `map'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/helper.rb:156:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb__525803379037861329_70142187091300'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template.rb:333:in `instrument'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:46:in `render_template'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/renderer/renderer.rb:27:in `render'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:100:in `_render_template'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:83:in `render_to_body'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/rendering.rb:25:in `render'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:16:in `render'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/goh/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:43:in `render'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
vendor/bundle/ruby/2.3.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:73:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/goh/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/Users/goh/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/goh/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```
# System configuration

**Ruby version:** 2.3.1p112
**Node.js:** 6.2.0

**Comment by deemytch** [comment]
+1

**Comment by fsinisi90** [comment]
+1

**Comment by gamesover** [comment]
I spent lots of time with [this article](http://nandovieira.com/using-es2015-with-asset-pipeline-on-ruby-on-rails). I feel very lost due to this issue.
If anyone wants to use es6, http://nandovieira.com/using-es6-with-asset-pipeline-on-ruby-on-rails is working.
